### ISSUE TITLE
Could we add sdists on pypi release?

### ISSUE THREAD

**Issue by goanpeca** [alisterburt/napari-tomoslice#6]
Hi @alisterburt

Currently pypi.org/project/napari-tomoslice/#files only uploaded wheels for the latest version. We also do not have github releases, so unlike `eulerangles` we cannot create a conda recipe at the moment.

Do you thing you could do a minor release to include the sdist files and not just the wheels?

Thanks!

**Comment by alisterburt** [comment]
Hi @goanpeca - done here too, v0.0.7 on pypi now, thanks!

**Comment by goanpeca** [comment]
Great, thanks!
